version: '3'

services:

  mariadb:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotfox
      MYSQL_USER: hotfox
      MYSQL_PASSWORD: hotfox

  php:
    build:
      dockerfile: './docker/php/Dockerfile'
      context: '.'
    depends_on:
      - mariadb
    volumes:
      - './:/var/www/html'
    cap_add:
      - SYS_ADMIN

  nginx:
    image: 'nginx:1.11-alpine'
    depends_on:
      - php
    ports:
      - '80:80'
    volumes:
      - './docker/nginx/conf.d:/etc/nginx/conf.d:ro'
      - './public:/var/www/html/public:ro'
      - './vendor:/var/www/html/vendor:ro'
  mailcatcher:
    image: sj26/mailcatcher
    ports:
      - "8080:1080"
